version: '2'
services:
  hisgateway-web:
    image: mophos/hisgateway-model2-web
    container_name: hisgateway-model2-web
    restart: always
    networks:
      gw2-network:
        ipv4_address: 10.222.222.9
  hisgateway-model2-api:
    image: mophos/hisgateway-model2-api
    restart: always
    container_name: hisgateway-api
    ports:
      - 8888:80
    volumes:
      - ${PATH_DNS}:/etc/resolv.conf
      - ${DATA_PATH}:/home/api/data
      - ./conf:/home/api/data/conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATA_PATH=/home/api/data
      - CONFIG_PATH=/home/api/data/conf
      - HOSPCODE=${HOSPCODE}
      - SECRET_KEY=${SECRET_KEY}
      - BROKER_URL=${BROKER_URL}
      - MINIFI_IP=http://10.222.222.8
    networks:
      gw2-network:
        ipv4_address: 10.222.222.7
  minifi:
    image: "mophos/hisgateway-minifi"
    container_name: "minifi"
    ports:
      - 8338:8338
    volumes:
      # - ./config/bootstrap.conf:/opt/minifi/minifi-current/conf/bootstrap.conf
      - ./logs:/opt/minifi/minifi-current/logs
      - ${DATA_PATH}:/home/api/data
      - /Users/tan/moph/Docker/his-gateway-model2-api/cert:/opt/cert
      - ./conf:/opt/minifi/minifi-current/config
    restart: always
    networks:
      gw2-network:
        ipv4_address: 10.222.222.8
  nginx:
    image: nginx:1.13.0-alpine
    container_name: nginx
    restart: always
    ports:
    - "${PORT}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      gw2-network:
        ipv4_address: 10.222.222.10
networks:
  gw2-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.222.0/24

